# Generated by Django 2.2.12 on 2020-08-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200831_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_text',
            new_name='text',
        ),
    ]
