# Generated by Django 2.2.12 on 2020-08-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200831_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='qualif',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='dating',
            new_name='time_frame',
        ),
    ]
